// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX5JJ3clew7wMoLOgsU1l6oihTBnA3RLE',
    appId: '1:996552366916:web:31c266912ae69900a85511',
    messagingSenderId: '996552366916',
    projectId: 'insuretech-7cd02',
    authDomain: 'insuretech-7cd02.firebaseapp.com',
    storageBucket: 'insuretech-7cd02.appspot.com',
    measurementId: 'G-WNZFV1MYMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHL0K21bXEtJgR5UVGHcpcMEotfSUsv28',
    appId: '1:996552366916:android:dcba6e1ab9185839a85511',
    messagingSenderId: '996552366916',
    projectId: 'insuretech-7cd02',
    storageBucket: 'insuretech-7cd02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoSpj3cVwg0SjWVNDzPmC5qiTkRyPJFug',
    appId: '1:996552366916:ios:80369d04b552b392a85511',
    messagingSenderId: '996552366916',
    projectId: 'insuretech-7cd02',
    storageBucket: 'insuretech-7cd02.appspot.com',
    iosBundleId: 'com.example.enterpriseMobilityAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoSpj3cVwg0SjWVNDzPmC5qiTkRyPJFug',
    appId: '1:996552366916:ios:80369d04b552b392a85511',
    messagingSenderId: '996552366916',
    projectId: 'insuretech-7cd02',
    storageBucket: 'insuretech-7cd02.appspot.com',
    iosBundleId: 'com.example.enterpriseMobilityAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX5JJ3clew7wMoLOgsU1l6oihTBnA3RLE',
    appId: '1:996552366916:web:077a6d5243fd8c07a85511',
    messagingSenderId: '996552366916',
    projectId: 'insuretech-7cd02',
    authDomain: 'insuretech-7cd02.firebaseapp.com',
    storageBucket: 'insuretech-7cd02.appspot.com',
    measurementId: 'G-KJW46Z8ENL',
  );

}